name: Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/ai00-run*